title:              Jay's Box
email:              jybae0601@gmail.com
description:        Blog for TIL
author:             Jay
baseurl:            "/jjay0303.github.io"
url:                "https://jjay0303.github.io"

# Social Profiles
twitter_username:   
github_username:    jjay0303
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
